mode: cluster
replicaCount: 1

image:
  repository: jthomperoo/predictive-horizontal-pod-autoscaler
  tag: ""
  pullPolicy: IfNotPresent

leaderElection:
  enabled: true

metrics:
  service:
    enabled: true
    port: 8080
